spring:
  application:
    name: eric-like

  mvc:
    servlet:
      path: /api

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eric_like_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 123456

  data:
    # Redis 配置
    redis:
      database: 0
      host: localhost
      password: 123456
      timeout: 5000
      port: 6379

  pulsar:
#    admin:
    #      service-url: http://192.168.31.217:6650
    client:
      service-url: pulsar://192.168.31.217:6650

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

knife4j:
  enable: true
  setting:
    language: zh_cn